version: "3"
services:
  api:
    container_name: api
    build: .
    ports: 
      - '8000:8000'
    volumes:
      - ./:/usr/src/api
    command: uvicorn dayflower.main:api --reload --host 0.0.0.0
  db:
    container_name: db
    build: ./db
    env_file: ./.env
    ports: 
      - '5432:5432'
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
