version: "3"
services:
  api:
    build: .
    ports: 
      - '8000:8000'
    container_name: api
    volumes:
      - ./:/usr/src/api
    command: uvicorn dayflower.main:api --reload --host 0.0.0.0
  db:
    build: ./db
    env_file: ./.env
    ports: 
      - '5432:5432'
    container_name: db
